### PR TITLE
Replace gaze with chokidar

### LINKED ISSUE #11: File watching and `--open` broken on Windows
As mentioned by @bdukes in https://github.com/tomekwi/elm-live/pull/10#issue-143414822 and https://github.com/tomekwi/elm-live/pull/10#issuecomment-201342084, we seem to have problems watching stuff and opening the browser.

### PR DESCRIPTION
**Pull request by bdukes**
Replacing gaze with the watcher from budo, chokidar, appears to fix the performance issue that was seen on Windows.  Because gaze was blocking when it started up, budo couldn't serve its files until gaze had finished finding all the elm files.  Even if I waited for budo to start before kicking gaze off, it still stalled budo from being able to reload (and there wasn't a good event to use for triggering gaze, so it would have used an arbitrary timeout value).

Using chokidar, which does its file finding asynchronously, there is no visible contention between the watcher and the server.  Additionally, making a change right after starting the server starts is seen and recompiled, without any significant delay from the watcher.

Fixes #11

### CODE REVIEW

File: source/elm-live.js [hunk 1]
```diff
@@ -112,7 +112,7 @@ ${ indent(String(elmMake.error), '  ') }
   }
 
   // Watch Elm files
-  const watcher = chokidar.watch('**/*.elm', { ignoreInitial: false, ignorePermissionErrors: true });
+  const watcher = chokidar.watch('**/*.elm', { ignoreInitial: true, ignorePermissionErrors: true });
```
Comment (tomekwi) [inline source/elm-live.js]: Why do we need `ignorePermissionErrors`? If it’s important, could you please add a regression test to make sure no-one breaks the behavior in the future?

As well as that, please add a test for `ignoreInitial` for the same reasons.

**Comment by tomekwi** [comment]
Does this solve the performance problems you mentioned in https://github.com/tomekwi/elm-live/issues/11#issuecomment-201971996? Does this solve the `--open` issue?

**Comment by bdukes** [comment]
This does solve the performance problems and the `--open` problem from #11.

File: source/elm-live.js (hunk 1 above)
Comment (bdukes) [inline source/elm-live.js]: I set `ignorePermissionErrors` on the assumption that it would be better to have a smoother experience than to be unable to use the tool because there are files that can't be accessed.  But I'll go ahead and turn it off, until someone complains, then we can decide the best path forward.

**Comment by tomekwi** [comment]
Great, thanks for adding the tests!

One more thing bothers me a bit. *gaze* used other event names: `added`, `changed`, `removed`. *chokidar* in turn uses `add`, `addDir`, `change`, `unlink` and `unlinkDir`. Therefore the log messages now look funny:

```sh
elm-live:
  You’ve change `RandomGifList.elm`. Rebuilding!

Success! Compiled 2 modules.                                        
Successfully generated index.html
[0128] 50ms       325KB GET    200 /
[0128] 228ms         0B GET    304 /

elm-live:
  You’ve add `newStuff.elm`. Rebuilding!

Success! Compiled 1 modules.                                        
Successfully generated index.html
[0152] 24ms       325KB GET    200 /
[0152] 21ms          0B GET    304 /

elm-live:
  You’ve unlink `newStuff.elm`. Rebuilding!

Success! Compiled 1 modules.                                        
Successfully generated index.html
[0165] 42ms       325KB GET    200 /
[0166] 77ms          0B GET    304 /
```

I see two ways forward – either map event names to log names through a simple object like `{ …, unlink: 'removed' }` – or explicitly listen to concrete events. Feel free to do it however you wish 🙂.

**Comment by bdukes** [comment]
:+1: I've added event name to display name mapping.

**Comment by tomekwi** [comment]
:+1: Perfect! Thanks a lot!
